const productos = [
    {
        id: 1,
        nombre: "Cascada de Humo (Buda)",
        descripcion: "Descripcion Uno",
        stock: 10,
        descuento: 0.0,
        precio: 1000,
    },
    {
        id: 2,
        nombre: "Cascada de Humo (Dragon)",
        descripcion: "Descripcion Dos",
        stock: 10,
        descuento: 0.15,
        precio: 1800,
    },
    {
        id: 3,
        nombre: "Tercer Producto",
        descripcion: "Descripcion Tres",
        stock: 10,
        descuento: 0,
        precio: 10000,
    },
    {
        id: 4,
        nombre: "Cascada de Humo (buho)",
        descripcion: "Descripcion Cuatro",
        stock: 10,
        descuento: 0.4,
        precio: 2500,
    },
    {
        id: 5,
        nombre: "Quinto Producto",
        descripcion: "Las cascadas de humo Inndomita contribuyen a la armonización del hogar, son utilizados para meditación y aromaterapia.",
        stock: 15,
        descuento: 0.15,
        precio: 1800,
    },
    {
        id: 6,
        nombre: "Lluvia de Humo",
        descripcion: "Descripcion Seis",
        stock: 10,
        descuento: 0.1,
        precio: 6000,
    },
    {
        id: 7,
        nombre: "Septimo Producto",
        descripcion: "Descripcion Siete",
        stock: 2,
        descuento: 0.25,
        precio: 4500,
    },
    {
        id: 8,
        nombre: "Quemador de palo santo (flor de loto)",
        descripcion: "Quemador de palo santo flor de loto",
        stock: 2,
        descuento: 0.3,
        precio: 4300,
    },
    {
        id: 9,
        nombre: "Quemador de Palo Santo",
        descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui magnam in nostrum repellat illo ad itaque aliquam pariatur officia, sunt quam! Quisquam esse, ad vel nulla quidem accusantium error maiores.",
        stock: 2,
        descuento: 0.15,
        precio: 1950,
    },
    
    {
        id: 10,
        nombre: "Hornillo",
        descripcion: " Descripcion ",
        stock: 2,
        descuento: 0.05,
        precio: 6000,
    }

]